# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidades_medida', '0001_initial'),
        ('relacionamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='id_unidade_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unidades_medida.UnidadeMedida'),
        ),
    ]
