# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0002_ingrediente_id_unidade_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulaingrediente',
            name='id_aula',
        ),
        migrations.RemoveField(
            model_name='aulaingrediente',
            name='id_ingrediente',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='ingredientes',
        ),
        migrations.DeleteModel(
            name='AulaIngrediente',
        ),
    ]
